run:
  skip-dirs:
    - testing
    - website
  allow-parallel-runners: true
  timeout: 5m
linters:
  enable:
    - gosec
    - unconvert
    - nlreturn
    - nestif
    - gomnd
    - stylecheck
    - gocyclo
    - maligned
    - dupl
    - misspell
    - unparam
    - whitespace
    - golint
    - interfacer
    - goconst
    - asciicheck
    - lll
    - gocritic
    - vet

linters-settings:
  lll:
    line-length: 140
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - log
    packages-with-error-message:
      - log: "logging is allowed only by fisherman/pkg/log"
      - gopkg.in/yaml.v2: "please use v3"
      - gopkg.in/yaml.v1: "please use v3"
