run:
  skip-dirs:
    - testing
  allow-parallel-runners: true
  timeout: 5m
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - gosec
    - unconvert
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - nlreturn
    - nestif
    - gomnd
    - unused
    - varcheck
    - stylecheck
    - gocyclo
    - dupl
    - misspell
    - unparam
    - whitespace
    - goconst
    - lll
    - gocritic
    - vet
    - asciicheck
    - cyclop
    - depguard
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - exhaustive
    - gochecknoinits
    - gocognit
    - gocritic
    - godot
    - gomnd
    - gomoddirectives
    - gosec
    - ifshort
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - prealloc
    - predeclared
    - promlinter
    - revive
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    # - wrapcheck

linters-settings:
  lll:
    line-length: 140
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - log
    packages-with-error-message:
      - log: "logging is allowed only by fisherman/pkg/log"
      - gopkg.in/yaml.v2: "please use v3"
      - gopkg.in/yaml.v1: "please use v3"
  tagliatelle:
    case:
      rules:
        yaml: kebab
  gosec:
    excludes:
      - G204
